apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f latest.yml --namespace {{ .Values.NAMESPACE }}
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: nextcloud-aio-apache
  name: nextcloud-aio-apache
  namespace: {{ .Values.NAMESPACE }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.APACHE_PORT }}-tcp
      port: {{ .Values.APACHE_PORT }}
      protocol: TCP
      targetPort: {{ .Values.APACHE_PORT }}
    - name: {{ .Values.APACHE_PORT }}-udp
      port: {{ .Values.APACHE_PORT }}
      protocol: UDP
      targetPort: {{ .Values.APACHE_PORT }}
  selector:
    io.kompose.service: nextcloud-aio-apache
